### PR TITLE
Hoist anonymous function declarations.

### LINKED ISSUE #183: Circular dependency doesn't work with anonymous function declaration
https://github.com/nicolo-ribaudo/std-esm-bug-anonymous-fn-decl

It works with node, but not with `@std/esm`:

```
~/Documenti/anonymous-function-declaration on  master is 📦  v1.0.0 via ⬢ v8.9.2 took 23s 
•100% ➜ node --experimental-modules main.mjs 
(node:16566) ExperimentalWarning: The ESM module loader is experimental.
fn

~/Documenti/anonymous-function-declaration on  master is 📦  v1.0.0 via ⬢ v8.9.2 
•100% ➜ node -r @std/esm main.mjs
TypeError: f is not a function
    at /home/nicolo/Documenti/anonymous-function-declaration/g.mjs:2:9
    at Object.<anonymous> (file:///home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/g.mjs:1)
    at Module._compile (file:///home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/file:/home/nicolo/Documenti/anonymous-function-declaration/module.js:635:30)

```

If I give a name to the function defined in `f.js` or I remove the first import from `main.js`, it works as I'd expect.
I'm not 100% sure that this is a bug, since I don't understand well the part of the spec related to modules and rollup behaves exactly like `@std/esm`.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Fixes #183

### CODE REVIEW

File: src/visitor/import-export.js [hunk 1]
```diff
@@ -123,14 +126,25 @@ class ImportExportVisitor extends Visitor {
     const { declaration } = node
     const { id, type } = declaration
 
-    if (id && (type === "FunctionDeclaration" ||
-               type === "ClassDeclaration")) {
+    if (type === "FunctionDeclaration" || (id && type === "ClassDeclaration")) {
+      const name = id ? id.name : encodeId("default")
```
Comment (nicolo-ribaudo) [inline src/visitor/import-export.js]: I didn't find a way of generatin an unique identifier. Is `default` + `ZWJ` ok?

File: src/visitor/import-export.js [hunk 2]
```diff
@@ -123,14 +126,25 @@ class ImportExportVisitor extends Visitor {
     const { declaration } = node
     const { id, type } = declaration
 
-    if (id && (type === "FunctionDeclaration" ||
-               type === "ClassDeclaration")) {
+    if (type === "FunctionDeclaration" || (id && type === "ClassDeclaration")) {
```
Comment (nicolo-ribaudo) [inline src/visitor/import-export.js]: Here I left the `id` check for classes because, even if tecnically they are declarations, they aren't hoisted and thus the difference between class expressions and declarations isn't noticeable.

**Comment by nicolo-ribaudo** [comment]
I just realized that the ast commit is unuseful because the output isn't visible to the user :sweat_smile:

File: test/output/anon-function/expected.mjs [hunk 3]
```diff
@@ -0,0 +1 @@
+_.e([["default",()=>default]]);function default() {}
```
Comment (benjamn) [inline test/output/anon-function/expected.mjs]: Instead of giving the anonymous function a name, I think you can just embed it inside the `_.e(...)` expression, like so:
```js
_.e([["default",(x=>()=>x)(function () {})]]);
```
The `x=>()=>x` bit is just an arrow function that takes a value and returns a function that always returns that value.

**Comment by jdalton** [comment]
Wow! Thank you @nicolo-ribaudo for putting in the PR and @benjamn for the review. 

This kind of help means a lot!

File: src/visitor/import-export.js (hunk 1 above)
Comment (jdalton) [reply src/visitor/import-export.js]: @nicolo-ribaudo
> I couldn't find a way of generating a unique identifier. Is `default` + `ZWJ` ok?

It's OK for this PR. I will follow up with a safe-name helper like [reify has](https://github.com/benjamn/reify/blob/3c002d12c32fa0be9bbbf648cb3b51777a6646d4/lib/import-export-visitor.js#L756-L761).

File: test/output/anon-function/expected.mjs (hunk 3 above)
Comment (nicolo-ribaudo) [reply test/output/anon-function/expected.mjs]: I think is is better as a declaration for two reasons:
-  Currently `@std/esm` does some work for keeping the original line numbers ([relevant test](https://github.com/standard-things/esm/tree/master/test/output/lines)). If anonymous declarations get moved to the top, it would be impossible.
- The `default` function name is more development-friendly when checking error stack traces (in a native implementation, their name would be `*default*`)

Comment (benjamn) [reply test/output/anon-function/expected.mjs]: Good points!

File: src/visitor/import-export.js [hunk 4]
```diff
@@ -2,13 +2,16 @@ import MagicString from "../magic-string.js"
...
 
+import encodeId from "../util/encode-id.js"
 import getNamesFromPattern from "../parse/get-names-from-pattern.js"
 import toStringLiteral from "../util/to-string-literal.js"
 
 const codeOfCR = "\r".charCodeAt(0)
 
 const { keys } = Object
 
+const functionPrefixRe = /^\s*(?:async\s*)?function(?:\s*\*)?/
```
Comment (jdalton) [inline src/visitor/import-export.js]: Is there a AST node way to detect the async bit that doesn't require a source sniff?

Comment (nicolo-ribaudo) [reply src/visitor/import-export.js]: Unfortunately not, that would probably only be exposed by a Concrete Syntax Tree.

Comment (jdalton) [reply src/visitor/import-export.js]: There's a [`pp.isAsyncFunction`](https://github.com/ternjs/acorn/blob/0a3fb09fbc596bcaa4ff6201a0f5b743f96953f1/src/statement.js#L52-L62) acorn method. Does that help?

Comment (nicolo-ribaudo) [reply src/visitor/import-export.js]: No, it only checks if the function is async.

That regex is used to know where the `async function` or `function *` part ends, and the parser doesn't expose this information.

Comment (jdalton) [reply src/visitor/import-export.js]: Ah ok cool. I can work with that. Thanks for the clarification!

**Comment by nicolo-ribaudo** [comment]
:tada:

File: src/visitor/import-export.js (hunk 1 above)
Comment (jdalton) [reply src/visitor/import-export.js]: Ok, so this is kinda neat. In making the safe-name helper I can just keep stacking ZWJs onto the name until there's no longer a conflict :yum:
